package test;

public class Test {
    public static void main(String[] args) {
        /*
            SelectSort
            WaterArea
            ReverseBinaryTree
            ReconstructBST
            PhoneNumberMnemonic
            FourSum
            WordSearch
            ClimbingStairs
            NextGreaterElement
            ConvertedSortedArrayToBST
            SearchForRange
            StaircaseTraversal
            SortKSortedArray
            KruskalMinSpanningTree
            DijkstraShortestPaths
            RotateImage
            PalindromicSubstrings
            ReverseInteger
            ConstructBinaryTreeFromPreorderAndInorderTraversal
            LongestCommonSubsequence
            ThreeSum
            ReverseString
            MedianOfTwoSortedArrays
            BalancedBrackets
            ZigZagTraverse
            Pow
            Permutations
            LeftViewBinaryTree
            SearchInRotatedSortedArray
            SurroundedRegions
            MaximumSubarray
            SpiralMatrixTraverse
            ProductOfArrayExceptSelf
            LevenshteinDistance
            DeleteNodeInLinkedList
            ReverseWordsInString
            RemoveNthNodeFromEndOfList
            MinRewards
            IntersectionLinkedList
            LRUCache
            SameBSTs
            MergeSort
            CloneGraph
            MinHeap
            QuickSort
            AddTwoNumbers
            MergeIntervals
            RiverSizes
            CountingSort
            DFSTreeTraverseRec
            AStarAlgo
            BreadthSearchFirst
            HouseRobber
            PrimMinSpanningTree
            BFSTreeTraverse
            UniquePaths
            LongestDecrSubseq
            ValidIPAddress
            PopulatingNextRightPointerInEachNode
            SubarraySort
            DepthFirstSearch
            SortList
            BinaryTreeZigzagLevelOrderTraverse
            Sqrt
            FindNodesDistanceK
            ValidateStartingCity
            MinNumberOfCoinsForChange
            MinNumberOfJumps
            NumberOfWaysToMakeChange
            Powerset
            ReverseLinkedList
            NodeDepths
            MaxPathSumInBinaryTree
            LongestNonDecrSubseq
            BinaryTreeDiameter
            KthSmallestElementInArray
            BestTimeToBuyAndSellStock
            BinarySearch
            FirstDuplicateValue
            LowestCommonAncestorOfBinarySearchTree
            LongestIncrSubSeq
            ValidateBinarySearchTree
            SameTree
            MinimumPassesOfMatrix
            CombinationSum
            HeapSort
            MaxSumIncreasingSubsequence
            BellmanFord
            BranchSums
            FirstPermutationIsSubstrSecondStr
            GenerateParentheses
            StringWithoutAAAorBBB
            BSTSuccessorSearch
            FindClosestValueInBST
            PalindromeLinkedList
            TopologicalSortDFSCycleGraph
            InsertSort
            SymmetricTree
            StringPermutation
            DFSTreeTraverse
            CycleLinkedList
            LargestRange
            LowestCommonAncestorOfBinaryTree
         */
    }
}