package test;

public class Test {
    public static void main(String[] args) {
        /*
            NextGreaterElement
            MergeSort
            CloneGraph
            BellmanFord
            Powerset
            MinHeap
            QuickSort
            DijkstraShortestPaths
            MaxPathSumInBinaryTree
            ProductOfArrayExceptSelf
            TopologicalSortDFSCycleGraph
            AddTwoNumbers
            SortKSortedArray
            ReverseInteger
            MinimumPassesOfMatrix
            CombinationSum
            ThreeSum
            BinaryTreeDiameter
            MaxSumIncreasingSubsequence
            LargestRange
            LongestIncrSubSeq
            LowestCommonAncestorOfBinaryTree
            MergeIntervals
            RiverSizes
            Sqrt
            FindNodesDistanceK
            ValidateStartingCity
            MinNumberOfCoinsForChange
            FindClosestValueInBST
            PhoneNumberMnemonic
            ClimbingStairs
            LongestNonDecrSubseq
            SearchInRotatedSortedArray
            WordSearch
            CountingSort
            StringPermutation
            ZigZagTraverse
            FirstPermutationIsSubstrSecondStr
            StaircaseTraversal
            Permutations
            LevenshteinDistance
            NodeDepths
            GenerateParentheses
            KruskalMinSpanningTree
            DFSTreeTraverseRec
            AStarAlgo
            BreadthSearchFirst
            HouseRobber
            PrimMinSpanningTree
            BFSTreeTraverse
            UniquePaths
            LongestDecrSubseq
            ValidIPAddress
            PopulatingNextRightPointerInEachNode
            SubarraySort
            DepthFirstSearch
            SortList
            BinaryTreeZigzagLevelOrderTraverse
            NumberOfWaysToMakeChange
            ReverseLinkedList
            KthSmallestElementInArray
            BestTimeToBuyAndSellStock
            BinarySearch
            FirstDuplicateValue
            LowestCommonAncestorOfBinarySearchTree
            ValidateBinarySearchTree
            SameTree
            HeapSort
            BranchSums
            StringWithoutAAAorBBB
            BSTSuccessorSearch
            PalindromeLinkedList
            InsertSort
            SymmetricTree
            DFSTreeTraverse
            CycleLinkedList
            SelectSort
            ReverseBinaryTree
            FourSum
            SearchForRange
            RotateImage
            PalindromicSubstrings
            ReverseString
            MedianOfTwoSortedArrays
            BalancedBrackets
            Pow
            LeftViewBinaryTree
            SurroundedRegions
            MaximumSubarray
            SpiralMatrixTraverse
            DeleteNodeInLinkedList
            ReverseWordsInString
            RemoveNthNodeFromEndOfList
            MinRewards
            IntersectionLinkedList
            LRUCache
            SameBSTs
         */
    }
}